name: NextEN Demo CI/CD

on: [push]

jobs:
  CICD_Next_Pipeline:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: cirix
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      -
        name: Push to docker hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: |
            cirix/nexten-demo:latest
            cirix/nexten-demo:0.0.1-SNAPSHOT
          push: true
